#imprimir_menu() NO FUNCIONARÁ

def imprimir_menu():
    print('Opciones: ')
    print('1). De acuerdo') # PUEDES MODIFICAR EL CÓDIGO Y EL CAMBIO ES PARA TODAS LAS INVOCACIONES (SE LE AGREGA UN PUNTO)
    print('2). En desacuerdo')
    print('3). No me interesa')
    
# SI USTED NO INVOCA LA FUNCIÓN, ES UN CÓDIGO MUERTO QUE NO HACE NADA
# PARA LLAMARLA SE LLAMA POR EL NOMBRE imprimir_menu()
# LLAMADO O INVOCACIÓN
#imprimir_menu()
# SE EJECUTA EL LA FUNCIÓN CUANDO SE HAYA DEFINIDO EL CÓDIGO PRIMERO

# SE PUEDE EJECUTAR CUANTAS VECES SE QUIERA
imprimir_menu()
imprimir_menu()
imprimir_menu()
# ES OBLIGATORIO PONER PARENTESIS LUEGO DL NOMBRE PARA QUE SE INTERPRETE COMO FUNCIÓN
